name: Check if can build
on: push

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: generate .env file
        run: |
          echo "GITHUB_KEY='${{ secrets.GITHUB_KEY }}'" > .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
